### ISSUE TITLE
Public key support

### ISSUE THREAD

**Issue by dspasyuk** [R3nPi2/cordova-plugin-sshclient#2]
Is there a way to use ssh public key with this client?

**Comment by R3nPi2** [comment]
Not at the moment.

You should add a custom function to support pubkey authentication based on original "Ganymed SSH-2 for Java" library.

T'hats the way I have added all the other functions on the plugin.

You will not find so much documentation on http://www.ganymed.ethz.ch/ssh2/, you must follow the code and see what happens... It was a "delicated" work for me, but funny.

Thanks for contacting, and if you want to contribute to this repo, just let me know.

**Comment by dspasyuk** [comment]
Thank you for quick response.
