### ISSUE TITLE
cordova plugin add https://github.com/R3nPi2/cordova-plugin-sshclient.git  failed

### ISSUE THREAD

**Issue by ltinerary** [R3nPi2/cordova-plugin-sshclient#3]
```sh
 Failed to fetch plugin https://github.com/R3nPi2/cordova-plugin-sshclient.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: An unknown git error occurred
```
I can't add this plugin.

By the way.

Do you mind if I use your code to publish to NPM?

**Comment by ltinerary** [comment]
Sorry, I found that I can add this plugin locally.

**Comment by R3nPi2** [comment]
There's a long time I don't develop with this plugin, so if you find any other issue I will appreciate your feedback.

I've just added it to npm, but don't test the installation, sorry, but not many time with lots of work XD

https://www.npmjs.com/package/@r3npi2/cordova-plugin-sshclient
